version: "3.8"

services:
  php:
    build:
      context: ./docker/php
    container_name: php_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t /var/www/html
